# Generated by Django 4.2.5 on 2024-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cipher_url', models.CharField(max_length=8)),
                ('plain_url', models.CharField(max_length=5000)),
                ('views', models.IntegerField(default=0)),
                ('url_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shorturl.userdetail')),
            ],
        ),
    ]
